[package]
name = "project_footprint"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/project_footprint.rs"
doctest = false

[dependencies]
gpui.workspace = true
log.workspace = true
project.workspace = true
settings.workspace = true
sysinfo.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
settings = { workspace = true, features = ["test-support"] }
